import "./globals.scss";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import Image from "next/image";
import Head from "next/head";
import ReactDOM from "react-dom";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  alternatives: {
    stylesheet: {},
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link
        id="1"
        rel="stylesheet"
        href="https://use.typekit.net/vex5gtt.css"
      />

      <body className={inter.className}>
        <Image
          alt="wood texture"
          src="/woodtexture.jpg"
          width={1000}
          height={1000}
          className="wood-texture"
        />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
